baseURL = "https://diary.benelog.net/"
languageCode = "ko-kr"
title = "diary.benelog.net"
theme = "hugo.386k"

[taxonomies]
   tag = "tags"
   categories = "categories"

[params]
    mainpagetitle = "일기 BBS"
    mainpagesubtitle = "주로 여가 활동에 대한 일기"
    showhugo = true
    loadonepass = true

[permalinks]
  post = "/:filename/"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "소개"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar
  [[menu.main]]
    identifier = "motivation"
    name = "동기유발"
    url = "/motivation/"
    weight = 15
  [[menu.main]]
    identifier = "posts"
    name = "모든 글"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
