baseURL = "https://diary.benelog.net/"
languageCode = "ko-kr"
title = "diary.benelog.net"

[taxonomies]
   tag = "tags"
   categories = "categories"

[params]
    mainpagetitle = "일기 BBS"
    mainpagesubtitle = "주로 여가 활동에 대한 일기"
    showhugo = true
    loadonepass = true
    customCSS = []

[pagination]
  pagerSize = 25

[permalinks]
  post = ":year/:contentbasename/"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "소개"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar
  [[menu.main]]
    identifier = "posts"
    name = "모든 글"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "태그"
    url = "/tags/"
    weight = 25
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 30
